SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_HILLBILLY"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_BALLAS"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_MEXICAN"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_FAMILY"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_MARABUNTE"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_SALVA"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_WEICHENG"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_LOST"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("GANG_1"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("GANG_2"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("GANG_9"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("GANG_10"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("FIREMAN"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("MEDIC"), `PLAYER`)
SetRelationshipBetweenGroups(1, GetHashKey("COP"), `PLAYER`)

-- I'll let the user uncomment these lines if needed
-- SetRelationshipBetweenGroups(1, GetHashKey("ARMY"), `PLAYER`)
-- SetRelationshipBetweenGroups(1, GetHashKey("SECURITY_GUARD"), `PLAYER`)